'use client'

import React from 'react'
import Dashboard from '@/components/Dashboard' // Adjust this import path as necessary

type TestResult = {
  id: string
  patientName: string
  dateOfBirth: string
  testType: string
  collectionDate: string
  testingDate: string | null
  status: 'Pending' | 'Done'
  serviceProvider: string
  medicalReferrer: string
  faxNumber: string
  email: string
  pdfView?: string // Added pdfView as an optional property
}
// This is mock data. In a real application, you'd fetch this data from an API.
const mockData: TestResult[] = [
  {
    id: '1',
    patientName: 'John Doe',
    dateOfBirth: '1980-05-15',
    testType: 'Blood Test',
    collectionDate: '2023-09-01',
    testingDate: '2023-09-02',
    status: 'Done',
    serviceProvider: 'ABC Testing',
    medicalReferrer: 'Greenwood Medical Center',
    faxNumber: '123-456-7890',
    email: 'johndoe@email.com',
  },
  {
    id: '2',
    patientName: 'John Doe',
    dateOfBirth: '1980-05-15',
    testType: 'Cholesterol Test',
    collectionDate: '2023-08-15',
    testingDate: null,
    status: 'Pending',
    serviceProvider: 'Lifeline Cliniclab',
    medicalReferrer: 'Greenwood Medical Center',
    faxNumber: '123-456-7890',
    email: 'johndoe@email.com',
  },
  {
    id: '3',
    patientName: 'Jane Smith',
    dateOfBirth: '1992-11-22',
    testType: 'Diabetes Test',
    collectionDate: '2023-09-10',
    testingDate: null,
    status: 'Pending',
    serviceProvider: 'HealthFirst Diagnostics',
    medicalReferrer: "Dr. Emily Chen's Office",
    faxNumber: '234-567-8901',
    email: 'janesmith@email.com',
  },
  {
    id: '4',
    patientName: 'Jane Smith',
    dateOfBirth: '1992-11-22',
    testType: 'Blood Test',
    collectionDate: '2023-07-20',
    testingDate: '2023-07-21',
    status: 'Done',
    serviceProvider: 'ABC Testing',
    medicalReferrer: "Dr. Emily Chen's Office",
    faxNumber: '234-567-8901',
    email: 'janesmith@email.com',
  },
  {
    id: '5',
    patientName: 'Bob Johnson',
    dateOfBirth: '1975-03-08',
    testType: 'Liver Function Test',
    collectionDate: '2023-08-05',
    testingDate: '2023-08-06',
    status: 'Done',
    serviceProvider: 'Lifeline Cliniclab',
    medicalReferrer: 'Sunset Valley Clinic',
    faxNumber: '345-678-9012',
    email: 'bobjohnson@email.com',
  },
  {
    id: '6',
    patientName: 'Bob Johnson',
    dateOfBirth: '1975-03-08',
    testType: 'Thyroid Test',
    collectionDate: '2023-06-30',
    testingDate: null,
    status: 'Pending',
    serviceProvider: 'HealthFirst Diagnostics',
    medicalReferrer: 'Sunset Valley Clinic',
    faxNumber: '345-678-9012',
    email: 'bobjohnson@email.com',
  },
  {
    id: '7',
    patientName: 'Alice Williams',
    dateOfBirth: '1988-07-12',
    testType: 'Lipid Panel',
    collectionDate: '2023-09-05',
    testingDate: '2023-09-06',
    status: 'Done',
    serviceProvider: 'ABC Testing',
    medicalReferrer: 'Oakwood Family Practice',
    faxNumber: '456-789-0123',
    email: 'alice.williams@email.com',
  },
  {
    id: '8',
    patientName: 'Charlie Brown',
    dateOfBirth: '1995-02-28',
    testType: 'Hemoglobin A1C',
    collectionDate: '2023-09-08',
    testingDate: null,
    status: 'Pending',
    serviceProvider: 'Lifeline Cliniclab',
    medicalReferrer: "Dr. Lucy van Pelt's Office",
    faxNumber: '567-890-1234',
    email: 'charlie.brown@email.com',
  },
  {
    id: '9',
    patientName: 'Emma Thompson',
    dateOfBirth: '1983-09-18',
    testType: 'Complete Blood Count',
    collectionDate: '2023-09-12',
    testingDate: '2023-09-13',
    status: 'Done',
    serviceProvider: 'HealthFirst Diagnostics',
    medicalReferrer: 'Riverside Community Hospital',
    faxNumber: '678-901-2345',
    email: 'emma.thompson@email.com',
  },
  {
    id: '10',
    patientName: 'Michael Chen',
    dateOfBirth: '1990-11-30',
    testType: 'Thyroid Stimulating Hormone',
    collectionDate: '2023-09-15',
    testingDate: null,
    status: 'Pending',
    serviceProvider: 'ABC Testing',
    medicalReferrer: "Dr. Sarah Johnson's Clinic",
    faxNumber: '789-012-3456',
    email: 'michael.chen@email.com',
  },
  {
    id: '11',
    patientName: 'Sophia Rodriguez',
    dateOfBirth: '1978-04-25',
    testType: 'Vitamin D',
    collectionDate: '2023-09-18',
    testingDate: '2023-09-19',
    status: 'Done',
    serviceProvider: 'Lifeline Cliniclab',
    medicalReferrer: 'Sunnydale Medical Group',
    faxNumber: '890-123-4567',
    email: 'sophia.rodriguez@email.com',
  },
  {
    id: '12',
    patientName: "Liam O'Connor",
    dateOfBirth: '1987-12-03',
    testType: 'Prostate-Specific Antigen',
    collectionDate: '2023-09-20',
    testingDate: null,
    status: 'Pending',
    serviceProvider: 'HealthFirst Diagnostics',
    medicalReferrer: "Dr. Robert Lee's Urology Center",
    faxNumber: '901-234-5678',
    email: 'liam.oconnor@email.com',
  },
  {
    id: '13',
    patientName: 'Olivia Kim',
    dateOfBirth: '1995-06-17',
    testType: 'Hemoglobin A1C',
    collectionDate: '2023-09-22',
    testingDate: '2023-09-23',
    status: 'Done',
    serviceProvider: 'ABC Testing',
    medicalReferrer: 'Maple Grove Endocrinology',
    faxNumber: '012-345-6789',
    email: 'olivia.kim@email.com',
  },
  {
    id: '14',
    patientName: 'Ethan Patel',
    dateOfBirth: '1982-02-14',
    testType: 'Lipid Panel',
    collectionDate: '2023-09-25',
    testingDate: null,
    status: 'Pending',
    serviceProvider: 'Lifeline Cliniclab',
    medicalReferrer: 'Heartcare Cardiovascular Center',
    faxNumber: '123-456-7890',
    email: 'ethan.patel@email.com',
  },
  {
    id: '15',
    patientName: 'Ava Wilson',
    dateOfBirth: '1993-08-09',
    testType: 'Comprehensive Metabolic Panel',
    collectionDate: '2023-09-28',
    testingDate: '2023-09-29',
    status: 'Done',
    serviceProvider: 'HealthFirst Diagnostics',
    medicalReferrer: "Dr. Jennifer Taylor's Family Practice",
    faxNumber: '234-567-8901',
    email: 'ava.wilson@email.com',
  },
  {
    id: '16',
    patientName: 'Noah Garcia',
    dateOfBirth: '1975-10-21',
    testType: 'Prostate-Specific Antigen',
    collectionDate: '2023-10-01',
    testingDate: null,
    status: 'Pending',
    serviceProvider: 'ABC Testing',
    medicalReferrer: 'Urology Associates of Greenville',
    faxNumber: '345-678-9012',
    email: 'noah.garcia@email.com',
  },
  {
    id: '17',
    patientName: 'Isabella Nguyen',
    dateOfBirth: '1989-03-27',
    testType: 'Thyroid Panel',
    collectionDate: '2023-10-03',
    testingDate: '2023-10-04',
    status: 'Done',
    serviceProvider: 'Lifeline Cliniclab',
    medicalReferrer: 'Endocrine Specialists of Boston',
    faxNumber: '456-789-0123',
    email: 'isabella.nguyen@email.com',
  },
  {
    id: '18',
    patientName: 'Mason Taylor',
    dateOfBirth: '1997-01-05',
    testType: 'Complete Blood Count',
    collectionDate: '2023-10-06',
    testingDate: null,
    status: 'Pending',
    serviceProvider: 'HealthFirst Diagnostics',
    medicalReferrer: "Dr. William Brown's Hematology Clinic",
    faxNumber: '567-890-1234',
    email: 'mason.taylor@email.com',
  },
  {
    id: '19',
    patientName: 'Grace Lee',
    dateOfBirth: '1984-12-11',
    testType: 'Iron Test',
    collectionDate: '2023-10-08',
    testingDate: '2023-10-09',
    status: 'Done',
    serviceProvider: 'ABC Testing',
    medicalReferrer: 'Northside Medical Center',
    faxNumber: '678-901-2345',
    email: 'grace.lee@example.com',
  },
  {
    id: '20',
    patientName: 'Daniel Martinez',
    dateOfBirth: '1979-07-23',
    testType: 'Allergy Test',
    collectionDate: '2023-10-10',
    testingDate: null,
    status: 'Pending',
    serviceProvider: 'Lifeline Cliniclab',
    medicalReferrer: 'Downtown Health Clinic',
    faxNumber: '789-012-3456',
    email: 'daniel.martinez@example.com',
  },
  {
    id: '21',
    patientName: 'Sophia Turner',
    dateOfBirth: '1991-05-30',
    testType: 'Kidney Function Test',
    collectionDate: '2023-10-12',
    testingDate: '2023-10-13',
    status: 'Done',
    serviceProvider: 'HealthFirst Diagnostics',
    medicalReferrer: 'Westside Family Practice',
    faxNumber: '890-123-4567',
    email: 'sophia.turner@example.com',
  },
  {
    id: '22',
    patientName: 'James Anderson',
    dateOfBirth: '1986-09-17',
    testType: 'Glucose Test',
    collectionDate: '2023-10-14',
    testingDate: null,
    status: 'Pending',
    serviceProvider: 'ABC Testing',
    medicalReferrer: 'Eastside Medical Group',
    faxNumber: '901-234-5678',
    email: 'james.anderson@example.com',
  },
  {
    id: '23',
    patientName: 'Emily Davis',
    dateOfBirth: '1994-03-22',
    testType: 'Vitamin B12',
    collectionDate: '2023-10-16',
    testingDate: '2023-10-17',
    status: 'Done',
    serviceProvider: 'Lifeline Cliniclab',
    medicalReferrer: 'Central Health Clinic',
    faxNumber: '012-345-6789',
    email: 'emily.davis@example.com',
  },
  {
    id: '24',
    patientName: 'David Wilson',
    dateOfBirth: '1981-11-29',
    testType: 'Hormone Panel',
    collectionDate: '2023-10-18',
    testingDate: null,
    status: 'Pending',
    serviceProvider: 'HealthFirst Diagnostics',
    medicalReferrer: 'Lakeside Medical Center',
    faxNumber: '123-456-7890',
    email: 'david.wilson@example.com',
  },
  {
    id: '25',
    patientName: 'Chloe Hernandez',
    dateOfBirth: '1996-08-03',
    testType: 'Electrolyte Panel',
    collectionDate: '2023-10-20',
    testingDate: '2023-10-21',
    status: 'Done',
    serviceProvider: 'ABC Testing',
    medicalReferrer: 'Hilltop Clinic',
    faxNumber: '234-567-8901',
    email: 'chloe.hernandez@example.com',
  },
  {
    id: '26',
    patientName: 'Benjamin Clark',
    dateOfBirth: '1977-02-19',
    testType: 'Blood Urea Nitrogen',
    collectionDate: '2023-10-22',
    testingDate: null,
    status: 'Pending',
    serviceProvider: 'Lifeline Cliniclab',
    medicalReferrer: 'Meadowbrook Family Practice',
    faxNumber: '345-678-9012',
    email: 'benjamin.clark@example.com',
  },
  {
    id: '27',
    patientName: 'Natalie Lewis',
    dateOfBirth: '1985-06-14',
    testType: 'Calcium Test',
    collectionDate: '2023-10-24',
    testingDate: '2023-10-25',
    status: 'Done',
    serviceProvider: 'HealthFirst Diagnostics',
    medicalReferrer: 'Mountain View Health Center',
    faxNumber: '456-789-0123',
    email: 'natalie.lewis@example.com',
  },
  {
    id: '28',
    patientName: 'Matthew Young',
    dateOfBirth: '1992-12-07',
    testType: 'Magnesium Test',
    collectionDate: '2023-10-26',
    testingDate: null,
    status: 'Pending',
    serviceProvider: 'ABC Testing',
    medicalReferrer: 'Riverbend Clinic',
    faxNumber: '567-890-1234',
    email: 'matthew.young@example.com',
  },
  {
    id: '29',
    patientName: 'Zoe King',
    dateOfBirth: '1983-01-11',
    testType: 'Phosphorus Test',
    collectionDate: '2023-10-28',
    testingDate: '2023-10-29',
    status: 'Done',
    serviceProvider: 'Lifeline Cliniclab',
    medicalReferrer: 'Pine Valley Medical Group',
    faxNumber: '678-901-2345',
    email: 'zoe.king@example.com',
  },
  {
    id: '30',
    patientName: 'Luke Wright',
    dateOfBirth: '1979-04-27',
    testType: 'Iron Test',
    collectionDate: '2023-10-30',
    testingDate: null,
    status: 'Pending',
    serviceProvider: 'HealthFirst Diagnostics',
    medicalReferrer: 'Forest Hill Clinic',
    faxNumber: '789-012-3456',
    email: 'luke.wright@example.com',
  },
  {
    id: '31',
    patientName: 'Sophie Scott',
    dateOfBirth: '1990-09-05',
    testType: 'Ferritin Test',
    collectionDate: '2023-11-01',
    testingDate: '2023-11-02',
    status: 'Done',
    serviceProvider: 'ABC Testing',
    medicalReferrer: 'Cedar Grove Medical Center',
    faxNumber: '890-123-4567',
    email: 'sophie.scott@example.com',
  },
  {
    id: '32',
    patientName: 'Ryan Green',
    dateOfBirth: '1987-05-16',
    testType: 'C-Reactive Protein',
    collectionDate: '2023-11-03',
    testingDate: null,
    status: 'Pending',
    serviceProvider: 'Lifeline Cliniclab',
    medicalReferrer: 'Willowbrook Health Clinic',
    faxNumber: '901-234-5678',
    email: 'ryan.green@example.com',
  },
  {
    id: '33',
    patientName: 'Amelia Baker',
    dateOfBirth: '1994-10-19',
    testType: 'ESR Test',
    collectionDate: '2023-11-05',
    testingDate: '2023-11-06',
    status: 'Done',
    serviceProvider: 'HealthFirst Diagnostics',
    medicalReferrer: 'Brookside Family Practice',
    faxNumber: '012-345-6789',
    email: 'amelia.baker@example.com',
  },
  {
    id: '34',
    patientName: 'Logan Adams',
    dateOfBirth: '1980-02-02',
    testType: 'Vitamin B12',
    collectionDate: '2023-11-07',
    testingDate: null,
    status: 'Pending',
    serviceProvider: 'ABC Testing',
    medicalReferrer: 'Hillside Medical Group',
    faxNumber: '123-456-7890',
    email: 'logan.adams@example.com',
  },
  {
    id: '35',
    patientName: 'Mia Nelson',
    dateOfBirth: '1993-07-25',
    testType: 'Folate Test',
    collectionDate: '2023-11-09',
    testingDate: '2023-11-10',
    status: 'Done',
    serviceProvider: 'Lifeline Cliniclab',
    medicalReferrer: 'Oakwood Health Clinic',
    faxNumber: '234-567-8901',
    email: 'mia.nelson@example.com',
  },
  {
    id: '36',
    patientName: 'Ethan Hill',
    dateOfBirth: '1988-03-13',
    testType: 'Cortisol Test',
    collectionDate: '2023-11-11',
    testingDate: null,
    status: 'Pending',
    serviceProvider: 'HealthFirst Diagnostics',
    medicalReferrer: 'Maple Leaf Clinic',
    faxNumber: '345-678-9012',
    email: 'ethan.hill@example.com',
  },
  {
    id: '37',
    patientName: 'Avery Roberts',
    dateOfBirth: '1996-06-08',
    testType: 'Testosterone Test',
    collectionDate: '2023-11-13',
    testingDate: '2023-11-14',
    status: 'Done',
    serviceProvider: 'ABC Testing',
    medicalReferrer: 'Parkview Medical Center',
    faxNumber: '456-789-0123',
    email: 'avery.roberts@example.com',
  },
  {
    id: '38',
    patientName: 'Oliver Phillips',
    dateOfBirth: '1982-09-21',
    testType: 'DHEA-Sulfate Test',
    collectionDate: '2023-11-15',
    testingDate: null,
    status: 'Pending',
    serviceProvider: 'Lifeline Cliniclab',
    medicalReferrer: 'Lakeside Family Practice',
    faxNumber: '567-890-1234',
    email: 'oliver.phillips@example.com',
  },
]
const generateUpdatedMockData = (): TestResult[] =>
  mockData.map((item) => ({
    ...item,
    pdfView: `https://example.com/test-results/${item.id}.pdf`,
  }))

// Generate the updated mock data
const updatedMockData = generateUpdatedMockData()

export default function DashboardPage() {
  return (
    <div className="container mx-auto p-4">
      <Dashboard data={updatedMockData} />
    </div>
  )
}
